<<<<<<< HEAD:Flask2/migrations/versions/965f68eb2def_initial_migration.py
"""initial migration

Revision ID: 965f68eb2def
Revises: 
Create Date: 2024-01-15 20:16:48.779871
=======
"""BDD

Revision ID: 24fcb3e706b7
Revises: 
Create Date: 2024-01-15 14:04:25.870706
>>>>>>> 95ffafe3e338dd421670825c382ab93d0e872fd6:Flask2/migrations/versions/24fcb3e706b7_bdd.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:Flask2/migrations/versions/965f68eb2def_initial_migration.py
revision = '965f68eb2def'
=======
revision = '24fcb3e706b7'
>>>>>>> 95ffafe3e338dd421670825c382ab93d0e872fd6:Flask2/migrations/versions/24fcb3e706b7_bdd.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_secret', sa.String(length=32), nullable=True),
    sa.Column('nom_evenement', sa.String(length=255), nullable=True),
    sa.Column('date_evenement', sa.Date(), nullable=True),
    sa.Column('lieu_evenement', sa.String(length=255), nullable=True),
    sa.Column('prix_ticket', sa.Float(), nullable=True),
    sa.Column('nomUtilisateur', sa.String(length=255), nullable=True),
    sa.Column('en_vente', sa.Boolean(), nullable=True),
    sa.Column('chemin_pdf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_secret')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('Bio', sa.String(length=9999), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ticket')
    # ### end Alembic commands ###
