"""a

Revision ID: 286852162ae1
Revises: 
Create Date: 2024-01-04 00:38:46.579797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286852162ae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('pdf_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_data', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
