"""empty message

Revision ID: 3ebba66a3601
Revises: b6349fa9ad86
Create Date: 2023-12-15 16:56:47.870258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebba66a3601'
down_revision = 'b6349fa9ad86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('achete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achete', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
