"""empty message

Revision ID: 582f3f0a0a02
Revises: e9725f898b81
Create Date: 2023-12-15 15:33:51.453640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582f3f0a0a02'
down_revision = 'e9725f898b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_vente', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('en_vente')

    # ### end Alembic commands ###
