"""empty message

Revision ID: e9725f898b81
Revises: 
Create Date: 2023-12-15 15:12:17.165549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9725f898b81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_evenement', sa.String(length=255), nullable=True),
    sa.Column('date_evenement', sa.Date(), nullable=True),
    sa.Column('lieu_evenement', sa.String(length=255), nullable=True),
    sa.Column('prix_ticket', sa.Float(), nullable=True),
    sa.Column('nomUtilisateur', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ticket')
    # ### end Alembic commands ###
