name: Black Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration de l'environnement Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Installation des dépendances
        run: pip install black
      - name: Black Lint
        run: |
          find . -type f -name '*.py' ! -path './versions/*' ! -name 'a.py' -exec black {} \;
