name: Black Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration de l'environnement Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Installation des dépendances
        run: pip install black
      - name: Black Lint
        run: black . --exclude env.py Tykz/migrations/versions/9e73ff12edd0_a.py
